services:
  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/2_data.sql
  api:
    container_name: profanator
    build: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SPRING_R2DBC_URL: r2dbc:postgres://db:5432/postgres
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
volumes:
  pgdata: