spring:
  r2dbc:
    url: r2dbc:postgres://localhost:5432/postgres
    username: postgres
    password: postgres

springdoc:
  webjars:
    prefix: ""
logging:
    api:
      configs:
        cache: DEBUG
      services:
        cache: DEBUG
server:
  error:
    include-stacktrace: on_param