spring:
  r2dbc:
    url: r2dbc:postgres://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgres://localhost:5432/postgres
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
springdoc:
  webjars:
    prefix: ""
logging:
    api:
      configs:
        cache: DEBUG
      services:
        cache: DEBUG
server:
  error:
    include-stacktrace: on_param