spring:
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
springdoc:
  webjars:
    prefix: ""
logging:
  level:
    org:
      springframework:
        r2dbc: INFO
        cache: DEBUG
    api:
      config:
        cache: DEBUG
      service:
        cache: DEBUG
server:
  error:
    include-stacktrace: on_param