INSERT INTO Proficiencies(name) VALUES
    ('Alchemy'),
    ('Architecture'),
    ('Blacksmith'),
    ('Bowcrafting'),
    ('Carpentry'),
    ('Tailoring'),
    ('Tinkering');

INSERT INTO Items(proficiency, name, qtbyproduction) VALUES
    (null, 'Ambar', 1),
    (null, 'Blood Berry', 1),
    (null, 'Blue Mushroom', 1),
    (null, 'Bones', 1),
    (null, 'Cobalt Ingot', 1),
    (null, 'Comet Fruit', 1),
    (null, 'Corrupted Root', 1),
    (null, 'Crystal Blossom', 1),
    (null, 'Dark Wood', 1),
    (null, 'Dung', 1),
    (null, 'Fermented Glowfruit', 1),
    (null, 'Flint', 1),
    (null, 'Floral Balm', 1),
    (null, 'Frost Needle', 1),
    (null, 'Ghastly Flame', 1),
    (null, 'Grog', 1),
    (null, 'Iron Ingot', 1),
    (null, 'Ixenite Ingot', 1),
    (null, 'Krekel Ingot', 1),
    (null, 'Large Bones', 1),
    (null, 'Leather', 1),
    (null, 'Minor Blue Shard', 1),
    (null, 'Minor Green Shard', 1),
    (null, 'Minor Purple Shard', 1),
    (null, 'Minor Red Shard', 1),
    (null, 'Minor Yellow Shard', 1),
    (null, 'Molten Core', 1),
    (null, 'Obsidian', 1),
    (null, 'Plant Fiber', 1),
    (null, 'Rough Cobalt', 1),
    (null, 'Rough Iron', 1),
    (null, 'Rough Ixenite', 1),
    (null, 'Rough Krekel', 1),
    (null, 'Rough Silver', 1),
    (null, 'Silver Ingot', 1),
    (null, 'Stick', 1),
    (null, 'Stone', 1),
    (null, 'Thick Leather', 1),
    (null, 'Thorn Algae', 1),
    (null, 'Volatile Essence', 1),
    (null, 'Wood', 1),
    -- ALCHEMY ITEMS
    ('Alchemy', 'Antidote', 1),
    ('Alchemy', 'Antidote Keg', 1),
    ('Alchemy', 'Antidote Bomb', 1),
    ('Alchemy', 'Explosion Keg', 1),
    ('Alchemy', 'Explosion Potion', 1),
    ('Alchemy', 'Explosion Potion Bomb', 1),
    ('Alchemy', 'Fertilizer Keg', 1),
    ('Alchemy', 'Fertilizer Potion Bomb', 1),
    ('Alchemy', 'Flame Keg', 1),
    ('Alchemy', 'Flame Potion', 1),
    ('Alchemy', 'Flame Potion Bomb', 1),
    ('Alchemy', 'Freezing Keg', 1),
    ('Alchemy', 'Freezing Potion', 1),
    ('Alchemy', 'Freezing Potion Bomb', 1),
    ('Alchemy', 'Health Keg', 1),
    ('Alchemy', 'Health Potion', 1),
    ('Alchemy', 'Health Potion Bomb', 1),
    ('Alchemy', 'Mana Keg', 1),
    ('Alchemy', 'Mana Potion', 1),
    ('Alchemy', 'Mana Potion Bomb', 1),
    ('Alchemy', 'Phase Potion Bomb', 1),
    ('Alchemy', 'Poison Keg', 1),
    ('Alchemy', 'Potion of Gills', 1),
    ('Alchemy', 'Poison Potion Bomb', 1),
    ('Alchemy', 'Strong Grog Keg', 1),
    ('Alchemy', 'Strong Grog Potion', 1),
    ('Alchemy', 'Strong Grog Potion Bomb', 1),
    -- ARCHITECTURE ITEMS
    ('Architecture', 'Flag', 1),
    ('Architecture', 'Guild Hall', 1),
    ('Architecture', 'Improvised Watchtower', 1),
    ('Architecture', 'Large Farm Lot', 1),
    ('Architecture', 'Large House', 1),
    ('Architecture', 'Medium Farm Lot', 1),
    ('Architecture', 'Medium House', 1),
    ('Architecture', 'Small Farm Lot', 1),
    ('Architecture', 'Small Ship', 1),
    ('Architecture', 'Straw House', 1),
    ('Architecture', 'Wooden Bridge', 1),
    -- BLACKSMITH ITEMS
    ('Blacksmith', 'Anchor', 1),
    ('Blacksmith', 'Arrowhead', 3),
    ('Blacksmith', 'Cobalt Plate Boots', 1),
    ('Blacksmith', 'Cobalt Plate Chest', 1),
    ('Blacksmith', 'Cobalt Plate Gauntlets', 1),
    ('Blacksmith', 'Cobalt Plate Helmet', 1),
    ('Blacksmith', 'Cobalt Plate Pauldrons', 1),
    ('Blacksmith', 'Cobalt Plate Waist', 1),
    ('Blacksmith', 'Bardiche', 1),
    ('Blacksmith', 'Battle Axe', 1),
    ('Blacksmith', 'Battle Hammer', 1),
    ('Blacksmith', 'Halberd', 1),
    ('Blacksmith', 'Iron Pickaxe', 1),
    ('Blacksmith', 'Iron Plate Boots', 1),
    ('Blacksmith', 'Iron Plate Chest', 1),
    ('Blacksmith', 'Iron Plate Gauntlets', 1),
    ('Blacksmith', 'Iron Plate Helmet', 1),
    ('Blacksmith', 'Iron Plate Pauldrons', 1),
    ('Blacksmith', 'Iron Plate Waist', 1),
    ('Blacksmith', 'Ixenite Plate Boots', 1),
    ('Blacksmith', 'Ixenite Plate Chest', 1),
    ('Blacksmith', 'Ixenite Plate Gauntlets', 1),
    ('Blacksmith', 'Ixenite Plate Helmet', 1),
    ('Blacksmith', 'Ixenite Plate Pauldrons', 1),
    ('Blacksmith', 'Ixenite Plate Waist', 1),
    ('Blacksmith', 'Krekel Plate Boots', 1),
    ('Blacksmith', 'Krekel Plate Chest', 1),
    ('Blacksmith', 'Krekel Plate Gauntlets', 1),
    ('Blacksmith', 'Krekel Plate Helmet', 1),
    ('Blacksmith', 'Krekel Plate Pauldrons', 1),
    ('Blacksmith', 'Krekel Plate Waist', 1),
    ('Blacksmith', 'Large Smelter', 1),
    ('Blacksmith', 'Primitive Axe', 1),
    ('Blacksmith', 'Primitive Hammer', 1),
    ('Blacksmith', 'Primitive Pickaxe', 1),
    ('Blacksmith', 'Silver Plate Boots', 1),
    ('Blacksmith', 'Silver Plate Chest', 1),
    ('Blacksmith', 'Silver Plate Gauntlets', 1),
    ('Blacksmith', 'Silver Plate Helmet', 1),
    ('Blacksmith', 'Silver Plate Pauldrons', 1),
    ('Blacksmith', 'Silver Plate Waist', 1),
    ('Blacksmith', 'Small Smelter', 1),
    ('Blacksmith', 'Spear', 1),
    ('Blacksmith', 'Sword', 1),
    -- BOWCRAFTING ITEMS
    ('Bowcrafting',	'Bleeding Arrow', 1),
    ('Bowcrafting',	'Blunt Arrow', 1),
    ('Bowcrafting',	'Bodkin Arrow', 3),
    ('Bowcrafting',	'Broadhead Arrow', 3),
    ('Bowcrafting',	'Explosive Arrow', 1),
    ('Bowcrafting',	'Flaming Arrow', 1),
    ('Bowcrafting',	'Flint Arrow', 3),
    ('Bowcrafting',	'Improvised Bow', 1),
    ('Bowcrafting',	'Poisonous Arrow', 1),
    ('Bowcrafting',	'Recurve Bow', 1),
    ('Bowcrafting',	'Shaft', 3),
    -- CARPENTRY ITEMS
    ('Carpentry', 'Arcane Staff', 1),
    ('Carpentry', 'Barrel', 1),
    ('Carpentry', 'Campfire', 1),
    ('Carpentry', 'Chest', 1),
    ('Carpentry', 'Empty Keg', 1),
    ('Carpentry', 'Lamp Post', 1),
    ('Carpentry', 'Range Target Dummy', 1),
    ('Carpentry', 'Scarecrow', 1),
    ('Carpentry', 'Shelf', 1),
    ('Carpentry', 'Small Table', 1),
    ('Carpentry', 'Spiked Club', 1),
    ('Carpentry', 'Staff', 1),
    ('Carpentry', 'Standing Torch', 1),
    ('Carpentry', 'Steering Wheel', 1),
    ('Carpentry', 'Training Dummy', 1),
    ('Carpentry', 'Wood Plank', 1),
    ('Carpentry', 'Wooden Bench', 1),
    ('Carpentry', 'Wooden Club', 1),
    -- TAILORING ITEMS
    ('Tailoring', 'Arcane Vestment Coat', 1),
    ('Tailoring', 'Arcane Vestment Hood', 1),
    ('Tailoring', 'Arcane Vestment Straps', 1),
    ('Tailoring', 'Bone Armor Belt', 1),
    ('Tailoring', 'Bone Armor Boots', 1),
    ('Tailoring', 'Bone Armor Breast Plate', 1),
    ('Tailoring', 'Bone Armor Gloves', 1),
    ('Tailoring', 'Bone Armor Helmet', 1),
    ('Tailoring', 'Bone Armor Shoulder Pad', 1),
    ('Tailoring', 'Large Bag', 1),
    ('Tailoring', 'Leather Armor Belt', 1),
    ('Tailoring', 'Leather Armor Boots', 1),
    ('Tailoring', 'Leather Armor Cowl', 1),
    ('Tailoring', 'Leather Armor Gauntlets', 1),
    ('Tailoring', 'Leather Armor Guard', 1),
    ('Tailoring', 'Leather Armor Spaulders', 1),
    ('Tailoring', 'Line Cloth', 1),
    ('Tailoring', 'Medium Bag', 1),
    ('Tailoring', 'Rope', 1),
    ('Tailoring', 'Small Bag', 1),
    -- TINKERING ITEMS
    ('Tinkering', 'Ambusher''s Ring', 1),
    ('Tinkering', 'Arcane Refiner Plan', 1),
    ('Tinkering', 'Band of Concentration', 1),
    ('Tinkering', 'Band of Longevity', 1),
    ('Tinkering', 'Empty Bursting Vial', 1),
    ('Tinkering', 'Empty Vial', 1),
    ('Tinkering', 'Heartseeker Ring', 1),
    ('Tinkering', 'Iron Nails', 3),
    ('Tinkering', 'Marauder''s Ring', 1),
    ('Tinkering', 'Sacred Shell Medallion', 1),
    ('Tinkering', 'Sigil of The Guardian', 1);

INSERT INTO Ingredients(product, name, quantity) VALUES
    ('Ambusher''s Ring', 'Silver Ingot', 2),
    ('Ambusher''s Ring', 'Ixenite Ingot', 1),
    ('Ambusher''s Ring', 'Minor Purple Shard', 1),
    ('Anchor', 'Iron Ingot', 10),
    ('Antidote', 'Empty Vial', 1),
    ('Antidote', 'Floral Balm', 3),
    ('Antidote', 'Blood Berry', 3),
    ('Antidote Bomb', 'Empty Bursting Vial', 1),
    ('Antidote Bomb', 'Volatile Essence', 1),
    ('Antidote Bomb', 'Blood Berry', 3),
    ('Antidote Bomb', 'Floral Balm', 4),
    ('Antidote Keg', 'Empty Keg', 1),
    ('Antidote Keg', 'Blood Berry', 60),
    ('Antidote Keg', 'Floral Balm', 60),
    ('Arcane Refiner Plan', 'Stone', 20),
    ('Arcane Refiner Plan', 'Wood', 10),
    ('Arcane Refiner Plan', 'Cobalt Ingot', 15),
    ('Arcane Refiner Plan', 'Molten Core', 4),
    ('Arcane Refiner Plan', 'Ghastly Flame', 5),
    ('Arcane Refiner Plan', 'Fermented Glowfruit', 5),
    ('Arcane Staff', 'Line Cloth', 2),
    ('Arcane Staff', 'Dark Wood', 4),
    ('Arcane Vestment Coat', 'Line Cloth', 35),
    ('Arcane Vestment Coat', 'Blue Mushroom', 5),
    ('Arcane Vestment Hood', 'Line Cloth', 40),
    ('Arcane Vestment Hood', 'Blue Mushroom', 7),
    ('Arcane Vestment Straps', 'Line Cloth', 60),
    ('Arcane Vestment Straps', 'Blue Mushroom', 15),
    ('Arrowhead', 'Iron Ingot', 1),
    ('Band of Concentration', 'Silver Ingot', 4),
    ('Band of Concentration', 'Minor Blue Shard', 1),
    ('Band of Longevity', 'Iron Ingot', 1),
    ('Band of Longevity', 'Silver Ingot', 3),
    ('Band of Longevity', 'Minor Red Shard', 1),
    ('Bardiche', 'Wood', 6),
    ('Bardiche', 'Leather', 1),
    ('Bardiche', 'Iron Ingot', 5),
    ('Barrel', 'Rope', 4),
    ('Barrel', 'Wood Plank', 12),
    ('Barrel', 'Iron Ingot', 4),
    ('Barrel', 'Iron Nails', 8),
    ('Battle Axe', 'Wood', 6),
    ('Battle Axe', 'Iron Ingot', 6),
    ('Battle Axe', 'Leather', 2),
    ('Battle Hammer', 'Wood', 8),
    ('Battle Hammer', 'Iron Ingot', 8),
    ('Battle Hammer', 'Leather', 2),
    ('Bleeding Arrow', 'Arrowhead', 1),
    ('Bleeding Arrow', 'Shaft', 1),
    ('Bleeding Arrow', 'Blood Berry', 2),
    ('Bleeding Arrow', 'Ghastly Flame', 2),
    ('Blunt Arrow', 'Arrowhead', 1),
    ('Blunt Arrow', 'Shaft', 1),
    ('Blunt Arrow', 'Iron Ingot', 1),
    ('Bodkin Arrow', 'Arrowhead', 3),
    ('Bodkin Arrow', 'Shaft', 3),
    ('Bone Armor Belt', 'Line Cloth', 4),
    ('Bone Armor Belt', 'Large Bones', 1),
    ('Bone Armor Boots', 'Line Cloth', 3),
    ('Bone Armor Boots', 'Bones', 3),
    ('Bone Armor Breast Plate', 'Line Cloth', 8),
    ('Bone Armor Breast Plate', 'Bones', 4),
    ('Bone Armor Breast Plate', 'Large Bones', 1),
    ('Bone Armor Gloves', 'Line Cloth', 2),
    ('Bone Armor Gloves', 'Bones', 2),
    ('Bone Armor Helmet', 'Line Cloth', 5),
    ('Bone Armor Helmet', 'Large Bones', 1),
    ('Bone Armor Shoulder Pad', 'Line Cloth', 5),
    ('Bone Armor Shoulder Pad', 'Large Bones', 1),
    ('Broadhead Arrow', 'Arrowhead', 3),
    ('Broadhead Arrow', 'Shaft', 3),
    ('Campfire', 'Wood', 5),
    ('Campfire', 'Flint', 1),
    ('Chest', 'Wood', 26),
    ('Chest', 'Rough Iron', 4),
    ('Cobalt Ingot', 'Rough Cobalt', 2),
    ('Cobalt Plate Boots', 'Cobalt Ingot', 4),
    ('Cobalt Plate Chest', 'Cobalt Ingot', 10),
    ('Cobalt Plate Gauntlets', 'Cobalt Ingot', 3),
    ('Cobalt Plate Gauntlets', 'Leather', 2),
    ('Cobalt Plate Helmet', 'Cobalt Ingot', 6),
    ('Cobalt Plate Pauldrons', 'Cobalt Ingot', 6),
    ('Cobalt Plate Waist', 'Cobalt Ingot', 5),
    ('Cobalt Plate Waist', 'Leather', 4),
    ('Empty Bursting Vial', 'Empty Vial', 1),
    ('Empty Bursting Vial', 'Crystal Blossom', 2),
    ('Empty Bursting Vial', 'Volatile Essence', 1),
    ('Empty Keg', 'Wood', 8),
    ('Empty Keg', 'Crystal Blossom', 2),
    ('Empty Keg', 'Rope', 2),
    ('Empty Keg', 'Wood Plank', 16),
    ('Empty Keg', 'Iron Ingot', 4),
    ('Empty Keg', 'Iron Nails', 8),
    ('Empty Vial', 'Crystal Blossom', 3),
    ('Explosion Keg', 'Empty Keg', 1),
    ('Explosion Keg', 'Fermented Glowfruit', 20),
    ('Explosion Keg', 'Molten Core', 40),
    ('Explosion Keg', 'Ghastly Flame', 40),
    ('Explosion Potion', 'Empty Vial', 1),
    ('Explosion Potion', 'Fermented Glowfruit', 1),
    ('Explosion Potion', 'Molten Core', 2),
    ('Explosion Potion', 'Ghastly Flame', 2),
    ('Explosion Potion Bomb', 'Empty Bursting Vial', 1),
    ('Explosion Potion Bomb', 'Fermented Glowfruit', 1),
    ('Explosion Potion Bomb', 'Volatile Essence', 2),
    ('Explosion Potion Bomb', 'Molten Core', 4),
    ('Explosion Potion Bomb', 'Ghastly Flame', 1),
    ('Explosive Arrow', 'Arrowhead', 1),
    ('Explosive Arrow', 'Shaft', 1),
    ('Explosive Arrow', 'Fermented Glowfruit', 1),
    ('Explosive Arrow', 'Volatile Essence', 4),
    ('Explosive Arrow', 'Molten Core', 6),
    ('Explosive Arrow', 'Ghastly Flame', 2),
    ('Fertilizer Keg', 'Empty Keg', 1),
    ('Fertilizer Keg', 'Dung', 150),
    ('Fertilizer Keg', 'Molten Core', 60),
    ('Fertilizer Potion Bomb', 'Empty Bursting Vial', 1),
    ('Fertilizer Potion Bomb', 'Dung', 5),
    ('Fertilizer Potion Bomb', 'Molten Core', 2),
    ('Flag', 'Wood', 25),
    ('Flag', 'Stone', 8),
    ('Flag', 'Rough Iron', 4),
    ('Flag', 'Leather', 5),
    ('Flame Keg', 'Empty Keg', 1),
    ('Flame Keg', 'Volatile Essence', 20),
    ('Flame Keg', 'Grog', 20),
    ('Flame Keg', 'Ghastly Flame', 20),
    ('Flame Potion', 'Empty Vial', 1),
    ('Flame Potion', 'Volatile Essence', 1),
    ('Flame Potion', 'Grog', 1),
    ('Flame Potion', 'Ghastly Flame', 1),
    ('Flame Potion Bomb', 'Empty Bursting Vial', 1),
    ('Flame Potion Bomb', 'Volatile Essence', 5),
    ('Flame Potion Bomb', 'Grog', 2),
    ('Flame Potion Bomb', 'Ghastly Flame', 2),
    ('Flaming Arrow', 'Arrowhead', 1),
    ('Flaming Arrow', 'Shaft', 1),
    ('Flaming Arrow', 'Fermented Glowfruit', 2),
    ('Flaming Arrow', 'Volatile Essence', 2),
    ('Flint Arrow', 'Flint', 1),
    ('Flint Arrow', 'Stick', 1),
    ('Freezing Keg', 'Empty Keg', 1),
    ('Freezing Keg', 'Frost Needle', 160),
    ('Freezing Keg', 'Blue Mushroom', 20),
    ('Freezing Potion', 'Empty Vial', 1),
    ('Freezing Potion', 'Frost Needle', 8),
    ('Freezing Potion', 'Grog', 1),
    ('Freezing Potion Bomb', 'Empty Bursting Vial', 1),
    ('Freezing Potion Bomb', 'Volatile Essence', 1),
    ('Freezing Potion Bomb', 'Frost Needle', 14),
    ('Freezing Potion Bomb', 'Grog', 2),
    ('Guild Hall', 'Stone', 1600),
    ('Guild Hall', 'Wood Plank', 1200),
    ('Guild Hall', 'Iron Ingot', 200),
    ('Guild Hall', 'Iron Nails', 200),
    ('Halberd', 'Wood', 6),
    ('Halberd', 'Leather', 1),
    ('Halberd', 'Iron Ingot', 4),
    ('Health Keg', 'Empty Keg', 1),
    ('Health Keg', 'Blood Berry', 120),
    ('Health Keg', 'Thorn Algae', 20),
    ('Health Potion', 'Empty Vial', 1),
    ('Health Potion', 'Blood Berry', 6),
    ('Health Potion', 'Thorn Algae', 1),
    ('Health Potion Bomb', 'Empty Bursting Vial', 1),
    ('Health Potion Bomb', 'Volatile Essence', 1),
    ('Health Potion Bomb', 'Blood Berry', 8),
    ('Health Potion Bomb', 'Thorn Algae', 2),
    ('Heartseeker Ring', 'Iron Ingot', 5),
    ('Heartseeker Ring', 'Silver Ingot', 1),
    ('Heartseeker Ring', 'Minor Green Shard', 1),
    ('Improvised Bow', 'Stick', 10),
    ('Improvised Bow', 'Flint', 4),
    ('Improvised Bow', 'Leather', 1),
    ('Improvised Bow', 'Line Cloth', 1),
    ('Improvised Watchtower', 'Wood', 12),
    ('Improvised Watchtower', 'Rope', 8),
    ('Improvised Watchtower', 'Wood Plank', 30),
    ('Improvised Watchtower', 'Iron Ingot', 12),
    ('Improvised Watchtower', 'Iron Nails', 60),
    ('Iron Ingot', 'Rough Iron', 2),
    ('Iron Nails', 'Iron Ingot', 1),
    ('Iron Pickaxe', 'Wood', 6),
    ('Iron Pickaxe', 'Iron Ingot', 4),
    ('Iron Pickaxe', 'Leather', 1),
    ('Iron Plate Boots', 'Iron Ingot', 4),
    ('Iron Plate Chest', 'Iron Ingot', 10),
    ('Iron Plate Gauntlets', 'Iron Ingot', 3),
    ('Iron Plate Gauntlets', 'Leather', 2),
    ('Iron Plate Helmet', 'Iron Ingot', 6),
    ('Iron Plate Pauldrons', 'Iron Ingot', 6),
    ('Iron Plate Waist', 'Iron Ingot', 5),
    ('Iron Plate Waist', 'Leather', 4),
    ('Ixenite Ingot', 'Rough Ixenite', 2),
    ('Ixenite Plate Boots', 'Ixenite Ingot', 4),
    ('Ixenite Plate Chest', 'Ixenite Ingot', 10),
    ('Ixenite Plate Gauntlets', 'Ixenite Ingot', 3),
    ('Ixenite Plate Gauntlets', 'Leather', 2),
    ('Ixenite Plate Helmet', 'Ixenite Ingot', 6),
    ('Ixenite Plate Pauldrons', 'Ixenite Ingot', 6),
    ('Ixenite Plate Waist', 'Ixenite Ingot', 5),
    ('Ixenite Plate Waist', 'Leather', 4),
    ('Krekel Ingot', 'Rough Krekel', 2),
    ('Krekel Plate Boots', 'Krekel Ingot', 4),
    ('Krekel Plate Chest', 'Krekel Ingot', 10),
    ('Krekel Plate Gauntlets', 'Krekel Ingot', 3),
    ('Krekel Plate Gauntlets', 'Leather', 2),
    ('Krekel Plate Helmet', 'Krekel Ingot', 6),
    ('Krekel Plate Pauldrons', 'Krekel Ingot', 6),
    ('Krekel Plate Waist', 'Krekel Ingot', 5),
    ('Krekel Plate Waist', 'Leather', 4),
    ('Lamp Post', 'Wood', 8),
    ('Lamp Post', 'Stone', 20),
    ('Lamp Post', 'Flint', 2),
    ('Lamp Post', 'Iron Ingot', 2),
    ('Lamp Post', 'Volatile Essence', 3),
    ('Large Bag', 'Line Cloth', 26),
    ('Large Bag', 'Leather', 2),
    ('Large Bag', 'Thick Leather', 15),
    ('Large Bag', 'Rough Iron', 1),
    ('Large Farm Lot', 'Dung', 40),
    ('Large Farm Lot', 'Wood', 60),
    ('Large Farm Lot', 'Wood Plank', 80),
    ('Large Farm Lot', 'Iron Nails', 60),
    ('Large House', 'Wood', 200),
    ('Large House', 'Stone', 830),
    ('Large House', 'Wood Plank', 240),
    ('Large House', 'Iron Ingot', 18),
    ('Large House', 'Iron Nails', 50),
    ('Large Smelter', 'Wood', 60),
    ('Large Smelter', 'Rough Iron', 120),
    ('Leather Armor Belt', 'Leather', 4),
    ('Leather Armor Belt', 'Thick Leather', 2),
    ('Leather Armor Belt', 'Line Cloth', 3),
    ('Leather Armor Boots', 'Leather', 2),
    ('Leather Armor Boots', 'Thick Leather', 1),
    ('Leather Armor Boots', 'Line Cloth', 2),
    ('Leather Armor Cowl', 'Leather', 2),
    ('Leather Armor Cowl', 'Thick Leather', 1),
    ('Leather Armor Cowl', 'Line Cloth', 3),
    ('Leather Armor Gauntlets', 'Leather', 1),
    ('Leather Armor Gauntlets', 'Thick Leather', 1),
    ('Leather Armor Gauntlets', 'Line Cloth', 1),
    ('Leather Armor Guard', 'Leather', 5),
    ('Leather Armor Guard', 'Thick Leather', 4),
    ('Leather Armor Guard', 'Line Cloth', 4),
    ('Leather Armor Spaulders', 'Leather', 4),
    ('Leather Armor Spaulders', 'Thick Leather', 2),
    ('Leather Armor Spaulders', 'Line Cloth', 3),
    ('Line Cloth', 'Plant Fiber', 5),
    ('Mana Keg', 'Empty Keg', 1),
    ('Mana Keg', 'Blue Mushroom', 160),
    ('Mana Potion', 'Empty Vial', 1),
    ('Mana Potion', 'Blue Mushroom', 8),
    ('Mana Potion Bomb', 'Empty Bursting Vial', 1),
    ('Mana Potion Bomb', 'Volatile Essence', 1),
    ('Mana Potion Bomb', 'Blue Mushroom', 10),
    ('Marauder''s Ring', 'Silver Ingot', 2),
    ('Marauder''s Ring', 'Cobalt Ingot', 1),
    ('Marauder''s Ring', 'Obsidian', 1),
    ('Medium Bag', 'Rough Iron', 1),
    ('Medium Bag', 'Line Cloth', 14),
    ('Medium Bag', 'Leather', 10),
    ('Medium Farm Lot', 'Dung', 18),
    ('Medium Farm Lot', 'Wood', 40),
    ('Medium Farm Lot', 'Wood Plank', 50),
    ('Medium Farm Lot', 'Iron Nails', 30),
    ('Medium House', 'Wood', 150),
    ('Medium House', 'Stone', 300),
    ('Medium House', 'Stick', 30),
    ('Medium House', 'Wood Plank', 45),
    ('Medium House', 'Iron Ingot', 22),
    ('Medium House', 'Iron Nails', 20),
    ('Phase Potion Bomb', 'Empty Bursting Vial', 1),
    ('Phase Potion Bomb', 'Volatile Essence', 1),
    ('Phase Potion Bomb', 'Blue Mushroom', 3),
    ('Phase Potion Bomb', 'Comet Fruit', 3),
    ('Phase Potion Bomb', 'Frost Needle', 4),
    ('Phase Potion Bomb', 'Ghastly Flame', 3),
    ('Poison Keg', 'Empty Keg', 1),
    ('Poison Keg', 'Dung', 30),
    ('Poison Keg', 'Corrupted Root', 240),
    ('Poison Keg', 'Thorn Algae', 60),
    ('Poison Potion Bomb', 'Empty Bursting Vial', 1),
    ('Poison Potion Bomb', 'Dung', 1),
    ('Poison Potion Bomb', 'Corrupted Root', 8),
    ('Poison Potion Bomb', 'Thorn Algae', 2),
    ('Poisonous Arrow', 'Arrowhead', 1),
    ('Poisonous Arrow', 'Shaft', 1),
    ('Poisonous Arrow', 'Molten Core', 1),
    ('Poisonous Arrow', 'Frost Needle', 1),
    ('Poisonous Arrow', 'Thorn Algae', 2),
    ('Potion of Gills', 'Empty Vial', 1),
    ('Potion of Gills', 'Comet Fruit', 2),
    ('Potion of Gills', 'Blood Berry', 3),
    ('Potion of Gills', 'Thorn Algae', 10),
    ('Primitive Axe', 'Stick', 8),
    ('Primitive Axe', 'Flint', 3),
    ('Primitive Hammer', 'Wood', 8),
    ('Primitive Hammer', 'Stone', 5),
    ('Primitive Hammer', 'Iron Ingot', 3),
    ('Primitive Pickaxe', 'Wood', 8),
    ('Primitive Pickaxe', 'Flint', 4),
    ('Range Target Dummy', 'Stick', 20),
    ('Range Target Dummy', 'Rope', 3),
    ('Range Target Dummy', 'Wood Plank', 3),
    ('Recurve Bow', 'Wood', 10),
    ('Recurve Bow', 'Flint', 8),
    ('Recurve Bow', 'Thick Leather', 2),
    ('Recurve Bow', 'Line Cloth', 1),
    ('Rope', 'Plant Fiber', 2),
    ('Sacred Shell Medallion', 'Cobalt Ingot', 3),
    ('Sacred Shell Medallion', 'Ambar', 1),
    ('Scarecrow', 'Wood', 6),
    ('Scarecrow', 'Line Cloth', 10),
    ('Scarecrow', 'Bones', 2),
    ('Scarecrow', 'Large Bones', 1),
    ('Scarecrow', 'Thick Leather', 5),
    ('Scarecrow', 'Rope', 4),
    ('Shaft', 'Stick', 1),
    ('Shelf', 'Wood Plank', 20),
    ('Shelf', 'Iron Nails', 10),
    ('Sigil of The Guardian', 'Silver Ingot', 4),
    ('Sigil of The Guardian', 'Minor Yellow Shard', 1),
    ('Silver Ingot', 'Rough Silver', 2),
    ('Silver Plate Boots', 'Silver Ingot', 4),
    ('Silver Plate Chest', 'Silver Ingot', 10),
    ('Silver Plate Gauntlets', 'Silver Ingot', 3),
    ('Silver Plate Gauntlets', 'Leather', 2),
    ('Silver Plate Helmet', 'Silver Ingot', 6),
    ('Silver Plate Pauldrons', 'Silver Ingot', 6),
    ('Silver Plate Waist', 'Silver Ingot', 5),
    ('Silver Plate Waist', 'Leather', 4),
    ('Small Bag', 'Line Cloth', 5),
    ('Small Bag', 'Leather', 2),
    ('Small Farm Lot', 'Dung', 6),
    ('Small Farm Lot', 'Wood', 20),
    ('Small Farm Lot', 'Wood Plank', 30),
    ('Small Farm Lot', 'Iron Nails', 10),
    ('Small Ship', 'Line Cloth', 80),
    ('Small Ship', 'Anchor', 1),
    ('Small Ship', 'Steering Wheel', 1),
    ('Small Ship', 'Rope', 30),
    ('Small Ship', 'Wood Plank', 170),
    ('Small Ship', 'Iron Nails', 60),
    ('Small Smelter', 'Wood', 20),
    ('Small Smelter', 'Rough Iron', 40),
    ('Small Table', 'Wood Plank', 12),
    ('Small Table', 'Iron Nails', 14),
    ('Spear', 'Wood', 6),
    ('Spear', 'Leather', 1),
    ('Spear', 'Iron Ingot', 4),
    ('Spiked Club', 'Wood', 5),
    ('Spiked Club', 'Line Cloth', 2),
    ('Spiked Club', 'Iron Nails', 12),
    ('Staff', 'Line Cloth', 1),
    ('Staff', 'Wood', 4),
    ('Standing Torch', 'Wood', 6),
    ('Standing Torch', 'Stick', 3),
    ('Standing Torch', 'Flint', 2),
    ('Standing Torch', 'Rope', 1),
    ('Steering Wheel', 'Wood', 8),
    ('Steering Wheel', 'Stone', 4),
    ('Steering Wheel', 'Rope', 1),
    ('Steering Wheel', 'Iron Ingot', 2),
    ('Steering Wheel', 'Iron Nails', 10),
    ('Straw House', 'Wood', 125),
    ('Straw House', 'Stone', 80),
    ('Straw House', 'Stick', 25),
    ('Straw House', 'Rough Iron', 15),
    ('Straw House', 'Rope', 8),
    ('Strong Grog Keg', 'Empty Keg', 1),
    ('Strong Grog Keg', 'Frost Needle', 20),
    ('Strong Grog Keg', 'Corrupted Root', 20),
    ('Strong Grog Keg', 'Floral Balm', 20),
    ('Strong Grog Keg', 'Grog', 20),
    ('Strong Grog Potion', 'Empty Vial', 1),
    ('Strong Grog Potion', 'Frost Needle', 1),
    ('Strong Grog Potion', 'Corrupted Root', 1),
    ('Strong Grog Potion', 'Floral Balm', 1),
    ('Strong Grog Potion', 'Grog', 1),
    ('Strong Grog Potion Bomb', 'Empty Bursting Vial', 1),
    ('Strong Grog Potion Bomb', 'Frost Needle', 2),
    ('Strong Grog Potion Bomb', 'Corrupted Root', 2),
    ('Strong Grog Potion Bomb', 'Floral Balm', 2),
    ('Strong Grog Potion Bomb', 'Grog', 2),
    ('Sword', 'Iron Ingot', 4),
    ('Sword', 'Leather', 1),
    ('Sword', 'Wood', 4),
    ('Training Dummy', 'Wood', 6),
    ('Training Dummy', 'Stick', 20),
    ('Training Dummy', 'Thick Leather', 8),
    ('Training Dummy', 'Rope', 6),
    ('Wood Plank', 'Wood', 4),
    ('Wooden Bench', 'Wood', 20),
    ('Wooden Bridge', 'Wood', 30),
    ('Wooden Bridge', 'Thick Leather', 6),
    ('Wooden Bridge', 'Rope', 8),
    ('Wooden Bridge', 'Wood Plank', 80),
    ('Wooden Bridge', 'Iron Nails', 80),
    ('Wooden Club', 'Wood', 5),
    ('Wooden Club', 'Line Cloth', 2);