CREATE TABLE IF NOT EXISTS Proficiencies(
	id SERIAL,
	name VARCHAR(255) UNIQUE,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP WITH TIME ZONE,
	version INTEGER,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Items(
	id SERIAL,
	proficiency VARCHAR(255),
	name VARCHAR(255) NOT NULL UNIQUE,
	qtbyproduction INTEGER NOT NULL CHECK (qtbyproduction > 0),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP WITH TIME ZONE,
	version INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY (proficiency) REFERENCES Proficiencies(name) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Ingredients(
	id SERIAL,
	product VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	quantity INTEGER NOT NULL CHECK (quantity > 0),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP WITH TIME ZONE,
	version INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY (product) REFERENCES Items(name) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (name) REFERENCES Items(name) ON DELETE CASCADE ON UPDATE CASCADE,
	UNIQUE (product, name)
);

CREATE TABLE IF NOT EXISTS Profanator_User(
    id SERIAL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    authorities VARCHAR(255) NOT NULL,
    accountnonexpired BOOLEAN DEFAULT TRUE,
    accountnonlocked BOOLEAN DEFAULT TRUE,
    credentialsnonexpired BOOLEAN DEFAULT TRUE,
    enabled BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (id)
);