spring:
  r2dbc:
    url: r2dbc:postgres://localhost:3306/profanator_db
    username: root
    password: root
springdoc:
  webjars:
    prefix: ""
logging:
  level:
    org:
      springframework:
        r2dbc: INFO
        cache: DEBUG
    api:
      config:
        cache: DEBUG
      service:
        cache: DEBUG
server:
  error:
  include-stacktrace: on_param