version: '3.8'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    networks:
      profanator-network:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profanatordb
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    container_name: api
    image: profanator_api_image
    restart: on-failure
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      profanator-network:
    environment:
      SPRING_R2DBC_URL: r2dbc:postgres://db:5432/profanatordb
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
volumes:
  pgdata:
networks:
  profanator-network:
    driver: bridge