version: '3.8'
services:
  db:
    container_name: db_container_test
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./../src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
